image: ubuntu

pages:
  script:
  - apk --no-cache add py2-pip python-dev py-pillow graphviz
  - pip install -r requirements.txt
  - sh build_docs.sh
  artifacts:
    paths:
    - public
  only:
  - master
