image: ubuntu

pages:
  script:
  - apt-get update -qq
  - apt-get install -y -qq python-pip python-dev python-pil graphviz python-qt4 libqtwebkit4
  - pip install -r requirements.txt
  - sh build_docs.sh
  artifacts:
    paths:
    - public
  only:
  - master
